server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:13306/login_demo?useUnicode=true&useSSL=false&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    database: 0
    host: localhost
    port: 16379

logging:
  level:
    root: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE